spring:
  application:
    name: account
  docker:
    compose:
      file: "./account/docker-compose.yml"
  datasource:
    url: "jdbc:postgresql://localhost:5432/account_database"
    username: postgres
    password: secret
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 600000
      poolName: accountComponentTestPool
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true