services:
  curso-branas-ddd-my-postgres-1:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5430"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10