services:
  curso-branas-ddd-my-postgres-1:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"