services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=account_database'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
